version: 2
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: Node Version
          command: node --version
      - run:
          name: Install Yarn
          command: npm install --global yarn
      - run: 
          name: yarn
          command: yarn
      - run: 
          name: test
          command: yarn test
      - run: 
          name: build
          command: yarn build
      - run:
          name: Aws
          command: aws
