version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Node Version
          command: node --version
      - run:
          name: Install Yarn
          command: npm install --global yarn
      - run: 
          name: yarn
          command: yarn
      - run: 
          name: test
          command: yarn test
  deploy:
    docker:
     - image: circleci/node:10
    steps:
     - checkout
     - run: 
        name: build
        command: yarn build
     - run:
        name: Install Aws
        command: sudo pip install awscli

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master