version: 2
jobs:
  build:
    docker:
      - image: mhart/alpine-node:10
    steps:
      - checkout
      - run:
          name: Node Version
          command: node --version
      - run:
          name: Install Yarn
          command: npm install --global yarn
