version: 2
jobs:
  build:
    docker:
      - image: mhart/alpine-node:10
    steps:
      - checkout
      - run:
          name: Greeting
          command: node --version
          command: npm install --global yarn
      - run:
          name: Print the Current Time
          command: date
